config/routes.rb
Rails.application.routes.draw do
  resources :checkins
  resources :rooms do
    collection { post :import }
  end
  resources :mentors do
    collection { post :import }
    collection { post :delete_all }
  end
  devise_for :users
  resources :orders do
    collection { get :scan }
    collection { post :scan_student }
  end
  resources :students do
    collection { post :import }
    collection { post :delete_all }
  end
  resources :users
  resources :items do
    collection { post :import }
    member { get :confirm }
  end

  root 'students#home'
  get 'renew/:id' => 'orders#renew'
  get 'return/:id' => 'orders#disable'
  get 'past_orders' => 'orders#old'

  post 'barcode_order' => 'orders#create_barcode_order'
  post 'barcode_checkin' => 'checkins#create_barcode_checkin'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/student.rb
class Student < ApplicationRecord
  has_many :orders
  has_many :items, through: :orders

  has_many :checkins
  has_many :rooms, through: :checkins

  validates :name, presence: true
  validates :email, presence: true
  validates :upc, presence: true

  require 'csv'

  def self.import(file)
  	CSV.foreach(file.path, headers:true) do |row|
  		Student.create! row.to_hash
  	end
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  def index
    @students = Student.all
  end

  def home
    @students = Student.all
    @mentors = Mentor.all
    @items = Item.all
    @upcoming = Room.upcoming?
  end

  def new
    @student = Student.new
  end

  def edit
  end

  def create
    @student = Student.new(student_params)
    if @student.save
      redirect_to :root, notice: 'Student was successfully created.'
    else
      render :new
    end
  end

  def import
    begin
      Student.import(params[:file])
      redirect_to :root, notice: 'Students successfully created from CSV.'
    rescue
      redirect_to :root, alert: 'Invalid CSV format.'
    end
  end

  def update
    if @student.update(student_params)
      redirect_to :root, notice: 'Student was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    if @student.orders.where(status: true).count == 0
      @student.destroy
      redirect_to :root, notice: 'Student was successfully destroyed.'
    else
      flash[:alert] = 'Students with active orders can not be deleted. Mark his/hers open orders as returned and try again.'
      redirect_to root_url
    end
  end

  def delete_all
    Student.delete_all
    redirect_to :root, notice: 'Students successfully destroyed.'
  end

  private
    def set_student
      @student = Student.find(params[:id])
    end

    def student_params
      params.require(:student).permit(:name, :email, :phone, :upc)
    end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/edit.html.erb
<body class="hold-transition skin-blue sidebar-mini">
<%= render 'layouts/header' %>
<div class="content-wrapper">

  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>
      Edit Student
    </h1>
    <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-home"></i> Home Page</a></li>
      <li class="active">Edit Student</li>
    </ol>
  </section>

  <!-- Main content -->
  <section class="content">
    <div class="row">
      <!-- left column -->
      <div class="col-md-6">
        <!-- general form elements -->
        <div class="box box-header">
          <div class="box-header with-border">
            <h3 class="box-title">Basic Information</h3>
          </div>
          <!-- /.box-header -->
          <!-- form start -->
          <%= form_for(@student) do |f| %>
            <% if @student.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

                <ul>
                <% @student.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
                </ul>
              </div>
            <% end %>

            <div class="box-body">
             <div class="form-group">
                <label>Full Name</label>
                <%= f.text_field :name, autocomplete: "off", placeholder: "Enter Full Name", class: "form-control", required: true %>
              </div>
             <div class="form-group">
                <label>E-mail Address</label>
                <%= f.text_field :email, autocomplete: "off", placeholder: "Enter Email Address", class: "form-control", required: true %>
              </div>
              <div class="form-group">
                <label>Phone Number</label>
                <%= f.text_field :phone, autocomplete: "off", placeholder: "Enter Phone Number", class: "form-control" %>
              </div>
              <div class="form-group">
                <label>Barcode UPC</label>
                <%= f.text_field :upc, autocomplete: "off", placeholder: "Enter Barcode", class: "form-control", required: true %>
              </div>
            <!-- /.box-body -->
            <div class="box-footer">
              <%= f.submit "Submit", class: "btn btn-primary"%>
            </div>
            <% end %>
        </div>
        <!-- /.box -->
      </div>
      <!--/.col (right) -->
    </div>
    </div>
    <!-- /.row -->
  </section>
  <!-- /.content -->

</div>
<%= render 'layouts/footer' %>
</body>

app/views/students/home.html.erb
<body class="hold-transition skin-blue sidebar-mini">
  <div class="wrapper">

    <%= render 'layouts/header' %>
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
      <!-- Content Header (Page header) -->
      <section class="content-header">
        <h1>
          Dashboard
          <small>Control panel</small>
        </h1>
        <ol class="breadcrumb">
          <li class="active">
            <a href="#">
              <i class="fa fa-home"></i>
              Home Page</a>
          </li>
        </ol>
      </section>

      <!-- Main content -->
      <section class="content">
        <!-- Small boxes (Stat box) -->
        <div class="row">
          <div class="col-lg-3 col-xs-6">
            <!-- small box -->
            <div class="small-box bg-aqua">
              <div class="inner">
                <h3><%=@items.sum(:quantity)%></h3>
                <p>Items Tracked</p>
              </div>
              <div class="icon">
                <i class="ion ion-search"></i>
              </div>
            </div>
          </div>
          <!-- ./col -->
          <div class="col-lg-3 col-xs-6">
            <!-- small box -->
            <div class="small-box bg-green">
              <div class="inner">
                <h3><%=@items.sum(:remaining_quantity)%></h3>
                <p>Items Available</p>
              </div>
              <div class="icon">
                <i class="ion ion-checkmark"></i>
              </div>
            </div>
          </div>
          <!-- ./col -->
          <div class="col-lg-3 col-xs-6">
            <!-- small box -->
            <div class="small-box bg-teal">
              <div class="inner">
                <h3><%= Checkin.students_at_hackathon.count - Checkin.students_left_hackathon.count %></h3>
                <p>Students Present</p>
              </div>
              <div class="icon">
                <i class="ion ion-person-stalker"></i>
              </div>
            </div>
          </div>
          <!-- ./col -->
          <div class="col-lg-3 col-xs-6">
            <!-- small box -->
            <div class="small-box bg-purple">
              <div class="inner">
                <h3><%= Checkin.mentors_at_hackathon.count - Checkin.mentors_left_hackathon.count %></h3>
                <p>Mentors Present</p>
              </div>
              <div class="icon">
                <i class="ion ion-android-time"></i>
              </div>
            </div>
          </div>
          <!-- ./col -->
        </div>
        <!-- /.row -->

        <div class="row">
          <div class="col-md-6">
            <div class="box">
              <div class="box-header with-border">
                <h3 class="box-title"><a href="<%= students_path %>">Students</a> (<%= @students.count %>)</h3>
              </div>
              <!-- /.box-header -->
              <div class="box-body">
                <table class="table table-bordered table-hover">
                  <tr>
                    <th>Name</th>
                    <th>E-mail</th>
                    <th>
                      <i class="ion ion-edit"></i>
                    </th>
                    <th>
                      <i class="ion ion-trash-b"></i>
                    </th>
                  </tr>
                  <% @students.each do |student| %>
                  <tr>
                    <td><%= student.name %></td>
                    <td><%= student.email %></td>
                    <td><%= link_to "", edit_student_path(student), { class: "ion ion-edit"} %></td>
                    <td>
                      <%= link_to student, method: :delete, data: { confirm: 'Are you sure?' } do %>
                      <i class="ion ion-trash-b"></i>
                      <% end %>
                    </td>
                  </tr>
                  <% end %>
                </table>
              </div>
              <% if @students.count > 0 %>
                <div class="box-footer">
                  Delete All
                  <%= link_to delete_all_students_path, method: :post, data: { confirm: 'Are you sure?' } do %>
                    <i class="ion ion-trash-b"></i>
                  <% end %>
                </div>
              <% end %>
              
            </div>
            <!-- /.box -->
          </div>
          <!-- ./col -->

        <div class="col-md-6">
            <div class="box">
              <div class="box-header with-border">
                <h3 class="box-title"><a href="<%= mentors_path %>">Mentors</a> (<%= @mentors.count %>)</h3>
              </div>
              <!-- /.box-header -->
              <div class="box-body">
                <table class="table table-bordered table-hover">
                  <tr>
                    <th>Name</th>
                    <th>E-mail</th>
                    <th>
                      <i class="ion ion-edit"></i>
                    </th>
                    <th>
                      <i class="ion ion-trash-b"></i>
                    </th>
                  </tr>
                  <% @mentors.each do |mentor| %>
                  <tr>
                    <td><%= mentor.name %></td>
                    <td><%= mentor.email %></td>
                    <td><%= link_to "", edit_mentor_path(mentor), { class: "ion ion-edit"} %></td>
                    <td>
                      <%= link_to mentor, method: :delete, data: { confirm: 'Are you sure?' } do %>
                      <i class="ion ion-trash-b"></i>
                      <% end %>
                    </td>
                  </tr>
                  <% end %>
                </table>
              </div>
              <% if @mentors.count > 0 %>
                <div class="box-footer">
                  Delete All
                  <%= link_to delete_all_mentors_path, method: :post, data: { confirm: 'Are you sure?' } do %>
                    <i class="ion ion-trash-b"></i>
                  <% end %>
                </div>
              <% end %>
              
            </div>
            <!-- /.box -->
          </div>
          <!-- ./col -->
        </div>
        <!-- /.row -->
      </section>
      <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
    <%= render 'layouts/footer' %>
    <script>
      $.widget.bridge('uibutton', $.ui.button);
    </script>
    <script>
      $(function () {
        $("#example1").DataTable();
        $('#example2').DataTable({
          "paging": true,
          "lengthChange": false,
          "searching": false,
          "ordering": true,
          "info": true,
          "autoWidth": false
        });
      });
    </script>
  </body>

app/views/students/index.html.erb
<body class="hold-transition skin-blue sidebar-mini">
  <div class="wrapper">
    <%= render 'layouts/header' %>
    <div class="content-wrapper">

      <!-- Content Header (Page header) -->
      <section class="content-header">
        <h1>
          Students Roster
        </h1>
        <ol class="breadcrumb">
          <li>
            <a href="#">
              <i class="fa fa-home"></i>
              Home Page</a>
          </li>
          <li class="active">Students Roster</li>
        </ol>
      </section>

      <section class="content">
        <div class="row">
          <div class="col-xs-12">
            <!-- Main data table -->
            <div class="box">

              <!-- /.box-header -->
              <div class="box-body">
                <table id="example1" class="table table-bordered table-striped">
                  <thead>
                    <tr>
                      <th>ID</th>
                      <th>Name</th>
                      <th>Email</th>
                      <th>Barcode</th>
                      <th>Edit</th>
                      <th>Delete</th>
                    </tr>
                  </thead>
                  <tbody>
                    <% @students.each do |student| %>
                    <tr>
                      <td><%= student.id %></td>
                      <td><%= student.name %></td>
                      <td><%= student.email %></td>
                      <td><%= student.upc %></td>
                      <td><%= link_to 'Edit', edit_student_path(student) %></td>
                      <td><%= link_to 'Delete', student, method: :delete, data: { confirm: 'Are you sure you want to delete this student?' } %></td>
                    </tr>
                    <% end %>
                  </tbody>
                </table>
              </div>
              <!-- /.box-body -->
            </div>
          </div>
        </div>
      </section>
    </div>
    <%= render 'layouts/footer' %>
  </div>
  <script>
    $(function () {
      $("#example1").DataTable();
      $('#example2').DataTable({
        "paging": true,
        "lengthChange": false,
        "searching": false,
        "ordering": true,
        "info": true,
        "autoWidth": false
      });
    });
  </script>
</body>

app/views/students/new.html.erb
<body class="hold-transition skin-blue sidebar-mini">
<%= render 'layouts/header' %>
<div class="content-wrapper">

  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>
      Add Student
    </h1>
    <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-home"></i> Home Page</a></li>
      <li class="active">Add Student</li>
    </ol>
  </section>

  <!-- Main content -->
  <section class="content">
    <div class="row">
      <!-- left column -->
      <div class="col-md-6">
        <!-- general form elements -->
        <div class="box box-header">
          <div class="box-header with-border">
            <h3 class="box-title">Basic Information</h3>
          </div>
          <!-- /.box-header -->
          <!-- form start -->
          <%= form_for(@student) do |f| %>
            <% if @student.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

                <ul>
                <% @student.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
                </ul>
              </div>
            <% end %>

            <div class="box-body">
             <div class="form-group">
                <label>Full Name</label>
                <%= f.text_field :name, autocomplete: "off", placeholder: "Enter Full Name", class: "form-control", required: true %>
              </div>
             <div class="form-group">
                <label>E-mail Address</label>
                <%= f.text_field :email, autocomplete: "off", placeholder: "Enter Email Address", class: "form-control", required: true %>
              </div>
              <div class="form-group">
                <label>Phone Number</label>
                <%= f.text_field :phone, autocomplete: "off", placeholder: "Enter Phone Number", class: "form-control" %>
              </div>
              <div class="form-group">
                <label>Barcode UPC</label>
                <%= f.text_field :upc, class: "form-control", placeholder: "Enter Barcode", required: true %>
              </div>
            <!-- /.box-body -->
            <div class="box-footer">
              <%= f.submit "Submit", class: "btn btn-primary"%>
            </div>
            <% end %>
        </div>
        <!-- /.box -->
      </div>
      <!--/.col (right) -->
    </div>

      <!-- right column -->
      <div class="col-md-6">
        <!-- general form elements -->
        <div class="box box-header">
          <div class="box-header with-border">
            <h3 class="box-title">Import CSV</h3>
          </div>
          <!-- /.box-header -->
          <!-- form start -->
            <div class="box-body">
             <div class="form-group">
                <label>Select File</label>
                <%= form_tag(import_students_path, multipart:true) do %>
                  <%= file_field_tag :file, class: "form-control" %>
                  <div class="box-footer">
                    <%= submit_tag "Submit", class: "btn btn-primary" %>
                  </div>
                <% end %>
              </div>
            <!-- /.box-body -->
            </div>
        <!-- /.box -->
        </div>
      <!--/.col (right) -->
      </div>
    </div>
    <!-- /.row -->
  </section>
  <!-- /.content -->

</div>
<%= render 'layouts/footer' %>
</body>