config/routes.rb
Rails.application.routes.draw do
  resources :checkins
  resources :rooms do
    collection { post :import }
  end
  resources :mentors do
    collection { post :import }
    collection { post :delete_all }
  end
  devise_for :users
  resources :orders do
    collection { get :scan }
    collection { post :scan_student }
  end
  resources :students do
    collection { post :import }
    collection { post :delete_all }
  end
  resources :users
  resources :items do
    collection { post :import }
    member { get :confirm }
  end

  root 'students#home'
  get 'renew/:id' => 'orders#renew'
  get 'return/:id' => 'orders#disable'
  get 'past_orders' => 'orders#old'

  post 'barcode_order' => 'orders#create_barcode_order'
  post 'barcode_checkin' => 'checkins#create_barcode_checkin'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/room.rb
class Room < ApplicationRecord
	has_many :checkins
  	has_many :students, through: :checkins
  	has_many :mentors, through: :checkins

	validates :name, presence: true
	validates :date, presence: true
	validates :time, presence: true

	require 'csv'

	def self.import(file)
	  CSV.foreach(file.path, headers:true) do |row|
	  	hash = row.to_hash
	  	hash['date'] = Date.strptime(hash['date'], '%m/%d/%Y')
	  	dt = hash['date'].strftime('%d/%m/%Y') + ' ' + hash['time']
	  	hash['time'] = dt.to_time(:utc)
	  	Room.create! hash
	  end
	end

	def self.upcoming?
		# hacky because Time.current doesn't use correct timezone in the where clause for some reason
		Room.where("date > ? OR date = ? AND time > ?", Date.today, Date.today, Time.current-7*60*60)
	end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
    @checkins = Checkin.roster(@room)
    @checkin = Checkin.new
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    dt = params[:room][:date] + ' ' + params[:room][:time]
    params[:room][:time] = dt.to_time(:utc)
    @room = Room.new(room_params)
    if @room.save
      redirect_to :root, notice: 'Room was successfully created.'
    else
      render :new
    end
  end

  def import
    begin
      Room.import(params[:file])
      redirect_to :root, notice: 'Items successfully created from CSV.'
    rescue
      redirect_to :back, alert: 'Invalid CSV format.'
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    if @room.update(room_params)
      redirect_to rooms_url, notice: 'Room was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    redirect_to rooms_url, notice: 'Room was successfully destroyed.'
  end

  def get_students 
    Student.all.map do |student| [student_id, student] 
    end
  end

  def get_mentors
    Mentor.all.map do |mentor| [mentor_id, mentor] 
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:name, :date, :time, :location, :upc)
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/edit.html.erb
<body class="hold-transition skin-blue sidebar-mini">
  <div class="wrapper">
    <%= render 'layouts/header' %>
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
      <!-- Content Header (Page header) -->
      <section class="content-header">
        <h1>
          Edit Room
        </h1>
        <ol class="breadcrumb">
          <li>
            <a href="#">
              <i class="fa fa-home"></i>
              Home Page</a>
          </li>
          <li class="active">Edit Room</li>
        </ol>
      </section>

      <!-- Main content -->
      <section class="content">
        <div class="row">
          <!-- left column -->
          <div class="col-md-6">
            <!-- general form elements -->
            <div class="box box-header">
              <div class="box-header with-border">
                <h3 class="box-title">Basic Information</h3>
              </div>
              <!-- /.box-header -->
              <!-- form start -->
              <%= form_for @room do |f| %>
              <% if @room.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(@room.errors.count, "error") %>
                  prohibited this item from being saved:</h2>
                <ul>
                  <% @room.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                  <% end %>
                </ul>
              </div>
              <% end %>
              <div class="box-body">
                <div class="form-group">
                  <label>Name</label>
                  <%= f.text_field :name, class: "form-control", placeholder: "Enter Name", required: true  %>
                </div>
                <div class="form-group">
                  <label>Date</label>
                  <%= f.text_field :date, class: "form-control datepicker", required: true  %>
                </div>
                <div class="form-group">
                  <label>Start Time</label>
                  <%= f.time_field :time, class: "form-control", placeholder: "Enter Start Time", required: true  %>
                </div>
                <div class="form-group">
                  <label>Location</label>
                  <%= f.text_field :location, class: "form-control", placeholder: "Enter Location" %>
                </div>
                <div class="form-group">
                  <label>Barcode UPC</label>
                  <%= f.text_field :upc, class: "form-control", placeholder: "Enter Barcode", required: true %>
                </div>
              </div>
              <!-- /.box-body -->
              <div class="box-footer">
                <%= f.submit "Submit", class: "btn btn-primary"%>
              </div>
              <% end %>

            </div>
            <!-- /.box -->
          </div>
          <!--/.col (right) -->
        </div>
        <!-- /.row -->
      </section>
      <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
    <footer class="main-footer">
      <div class="pull-right hidden-xs">
        <b>Version</b>
        0.1
      </div>
      Content available under
      <a href="http://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Attribution-ShareAlike 4.0</a>.
    </footer>
    <!-- ./wrapper -->
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>
      $.widget.bridge('uibutton', $.ui.button);
      $('.datepicker').datepicker({format: 'yyyy/mm/dd'});
    </script>
  </body>

app/views/rooms/index.html.erb
<body class="hold-transition skin-blue sidebar-mini">
  <div class="wrapper">
    <%= render 'layouts/header' %>
    <div class="content-wrapper">

      <!-- Content Header (Page header) -->
      <section class="content-header">
        <h1>
          Workshops
          <small>Items</small>
        </h1>
        <ol class="breadcrumb">
          <li>
            <a href="#">
              <i class="fa fa-home"></i>
              Home Page</a>
          </li>
          <li class="active">Workshops</li>
        </ol>
      </section>

      <section class="content">
        <div class="row">
          <div class="col-xs-12">
            <!-- Main data table -->
            <div class="box">

              <!-- /.box-header -->
              <div class="box-body">
                <table id="example1" class="table table-bordered table-striped">
                  <thead>
                    <tr>
                      <th>
                        <i class="fa fa-map-marker"></i>
                      </th>
                      <th>ID</th>
                      <th>Name</th>
                      <th>Date</th>
                      <th>Time</th>
                      <th>Location</th>
                      <th>Edit</th>
                      <th>Delete</th>
                    </tr>
                  </thead>
                  <tbody>
                    <% @rooms.each do |room| %>
                    <tr>
                      <td><%= link_to "", room_path(room), { class: "fa fa-map-marker"} %></td>
                      <td><%= room.id %></td>
                      <td><%= link_to room.name, room_path(room)  %></td>
                      <td><%= room.date %></td>
                      <td><%= room.time.strftime("%I:%M %p") %></td>
                      <td><%= room.location %></td>
                      <td><%= link_to 'Edit', edit_room_path(room) %></td>
                      <td><%= link_to 'Delete', room, method: :delete, data: { confirm: 'Are you sure you want to delete this room?' } %></td>
                    </tr>
                    <% end %>
                  </tbody>
                </table>
              </div>
              <!-- /.box-body -->
            </div>
          </div>
        </div>
      </section>
    </div>
    <%= render 'layouts/footer' %>
  </div>
  <script>
    $(function () {
      $("#example1").DataTable();
      $('#example2').DataTable({
        "paging": true,
        "lengthChange": false,
        "searching": false,
        "ordering": true,
        "info": true,
        "autoWidth": false
      });
    });
  </script>
</body>

app/views/rooms/new.html.erb
<body class="hold-transition skin-blue sidebar-mini">
  <div class="wrapper">
    <%= render 'layouts/header' %>
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
      <!-- Content Header (Page header) -->
      <section class="content-header">
        <h1>
          Add Room
        </h1>
        <ol class="breadcrumb">
          <li>
            <a href="#">
              <i class="fa fa-home"></i>
              Home Page</a>
          </li>
          <li class="active">Add Room</li>
        </ol>
      </section>

      <!-- Main content -->
      <section class="content">
        <div class="row">
          <!-- left column -->
          <div class="col-md-6">
            <!-- general form elements -->
            <div class="box box-header">
              <div class="box-header with-border">
                <h3 class="box-title">Basic Information</h3>
              </div>
              <!-- /.box-header -->
              <!-- form start -->
              <%= form_for @room do |f| %>
              <% if @room.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(@room.errors.count, "error") %>
                  prohibited this item from being saved:</h2>
                <ul>
                  <% @room.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                  <% end %>
                </ul>
              </div>
              <% end %>
              <div class="box-body">
                <div class="form-group">
                  <label>Name</label>
                  <%= f.text_field :name, class: "form-control", placeholder: "Enter Name", required: true  %>
                </div>
                <div class="form-group">
                  <label>Date</label>
                  <%= f.text_field :date, class: "form-control datepicker", required: true  %>
                </div>
                <div class="form-group">
                  <label>Start Time</label>
                  <%= f.time_field :time, class: "form-control", placeholder: "Enter Start Time", required: true  %>
                </div>
                <div class="form-group">
                  <label>Location</label>
                  <%= f.text_field :location, class: "form-control", placeholder: "Enter Location" %>
                </div>
              </div>
              <!-- /.box-body -->
              <div class="box-footer">
                <%= f.submit "Submit", class: "btn btn-primary"%>
              </div>
              <% end %>
            </div>
            <!-- /.box -->
          </div>
          <!--/.col (right) -->

          <!-- right column -->
          <div class="col-md-6">
            <!-- general form elements -->
            <div class="box box-header">
              <div class="box-header with-border">
                <h3 class="box-title">Import CSV</h3>
              </div>
              <!-- /.box-header -->
              <!-- form start -->
                <div class="box-body">
                 <div class="form-group">
                    <label>Select File</label>
                    <%= form_tag(import_rooms_path, multipart:true) do %>
                      <%= file_field_tag :file, class: "form-control" %>
                      <div class="box-footer">
                        <%= submit_tag "Submit", class: "btn btn-primary" %>
                      </div>
                    <% end %>
                  </div>
                <!-- /.box-body -->
                </div>
            <!-- /.box -->
            </div>
          <!--/.col (right) -->
          </div>
        </div>
        <!-- /.row -->
      </section>
      <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
    <footer class="main-footer">
      <div class="pull-right hidden-xs">
        <b>Version</b>
        0.1
      </div>
      Content available under
      <a href="http://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Attribution-ShareAlike 4.0</a>.
    </footer>
    <!-- ./wrapper -->
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>
      $.widget.bridge('uibutton', $.ui.button);
      $('.datepicker').datepicker({format: 'yyyy/mm/dd'});
    </script>
  </body>

app/views/rooms/show.html.erb
<body class="hold-transition skin-blue sidebar-mini">
  <div class="wrapper">
    <%= render 'layouts/header' %>
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
      <!-- Content Header (Page header) -->
      <section class="content-header">
        <h1><%= @room.name %></h1>
        <ol class="breadcrumb">
          <li><a href="#"><i class="fa fa-home"></i>Home Page</a></li>
          <li class="active">Check In</li>
        </ol>
      </section>

      <!-- Main content -->
      <section class="content">
        <div class="row">
          <!-- left column -->
          <div class="col-md-6">
           <div class="box box-header">
              <div class="box-header with-border">
                <h3 class="box-title">Scan Student</h3>
              </div>
              
              <div class="box-body">
                <div id='barcode-scanner'></div>
                  <div id='is_room' style="display: none;">
                    <%= 0 %>
                  </div>
                  <div id='item_or_room_id' style="display: none;">
                    <%= @room.id %>
                  </div>
              </div>
              <!-- /.box-body -->
              
            </div>
            <!-- /.box -->
          </div>
          <!--/.col (left) -->
          <!-- right column -->
          <div class="col-md-6">
           <div class="box box-header">
              <div class="box-header with-border">
                <h3 class="box-title">Room Roster (<%= @checkins.count %>)</h3>
              </div>
              
              <div class="box-body">
                <table class="table table-bordered table-hover">
                  <tr>
                    <th>Name</th>
                    <th>Timestamp</th>
                    <th>Status</th>
                    <th>
                      <i class="ion ion-trash-b"></i>
                    </th>
                  </tr>
                  <% @checkins.each do |checkin| %>
                  <tr>
                    <% if checkin.is_mentor && checkin.mentor %>
                      <td><%= checkin.mentor.name %></td>
                      <td><%= checkin.created_at.strftime("%m/%d/%Y, %H:%M:%S") %></td>
                      <td>Mentor</td>
                    <% elsif checkin.student %>
                      <td><%= checkin.student.name %></td>
                      <td><%= checkin.created_at.strftime("%m/%d/%Y, %H:%M:%S") %></td>
                      <td>Student</td>
                    <% end %>
                    <td>
                      <%= link_to checkin, method: :delete, data: { confirm: 'Are you sure?' } do %>
                      <i class="ion ion-trash-b"></i>
                      <% end %>
                    </td>
                  </tr>
                  <% end %>
                </table>
              </div>
              <!-- /.box-body -->
              
            </div>
            <!-- /.box -->
          </div>
 
          <!--/.col (right) -->
        </div>
        <!-- /.row -->
        <div class="row">
          <!-- left column -->
          <div class="col-md-6">
           <div class="box box-header">
              <div class="box-header with-border">
                <h3 class="box-title">Manual Check-In</h3>
              </div>
              
              <%= form_for @checkin do |f| %>
                <% if @checkin.errors.any? %>
                  <div id="error_explanation">
                    <h2><%= pluralize(@checkin.errors.count, 'error') %> prohibited this check-in from being saved:</h2>
                    <ul>
                      <% @checkin.errors.full_messages.each do |message| %>
                        <li><%= message %></li>
                      <% end %>
                    </ul>
                  </div>
                <% end %>

                <div class="box-body">
                  <div class="form-group">
                    <label>Mentor?</label>
                    <%= f.select(:is_mentor, options_for_select([true, false]), { include_blank: true } , { class: 'dropdown' , required: true }) %>
                  </div>
                  <div class="form-group">
                    <label>Student</label>
                    <br>
                    <%= f.select(:student_id, get_students, { include_blank: true } , { class: 'dropdown' , required: false }) %>
                  </div>
                  <div class="form-group">
                    <label>Mentor</label>
                    <br>
                    <%= f.select(:mentor_id, get_mentors, { include_blank: true } , { class: 'dropdown' , required: false }) %>
                  </div>
                  <%= f.number_field :room_id, :value => @room.id, :hidden => true %>
                </div>
                <!-- /.box-body -->
                <div class="box-footer">
                  <%= f.submit 'Submit', class: 'btn btn-primary' %>
                </div>
              <% end %>
              <!-- /.box-body -->
              
            </div>
            <!-- /.box -->
          </div>

          <div class="col-md-6">
            <div class="box box-header">
              <div class="box-header with-border">
                <h3 class="box-title">Raffle for Workshop </h3>
              </div>
              <div class="box-body">
                <input style="float: left" id="jo" type="submit" name="commit" value="Generate Winner" class="btn btn-primary" data-disable-with="Submit" />
                <div style="float: right; margin-right: 25px; margin-top: 5px; font-size: 17px" id="winner"></div>
              </div>
            </div>
          </div>
        </div>
      </section>
      <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
    <%= render 'layouts/footer' %>
    <!-- ./wrapper -->
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>
      $(document).ready(function () {
        $.widget.bridge('uibutton', $.ui.button);
        $('.datepicker').datepicker({format: 'yyyy/mm/dd'});
        $('.dropdown').select2( {
          theme: "bootstrap"
        });
        var names = [];
        var tablex = document.getElementsByTagName('table');
        console.log(tablex);
        var table = document.getElementsByTagName('table')[0];
        console.log(table)
        var rows = table.rows;
        var mentorcount = 0;
        for (var i = 1; i < rows.length; i++) {
            var name = rows[i].cells[0].innerHTML;
            var status = rows[i].cells[2].innerHTML;
            console.log(name + " " + status)
            if (status != "Student") {
              mentorcount ++;
              continue;
            }  else {
              names.push(name);
            }
        }
        $("#jo").click(function() {
          var randomNum = Math.floor((Math.random() * Math.floor(rows.length-1-mentorcount)));
          var winner = names[randomNum]
          console.log(randomNum)
          console.log(winner)
          $("#winner").text(winner + " wins!")
        });
      });
    </script>
  </div>
</body>