config/routes.rb
Rails.application.routes.draw do
  resources :checkins
  resources :rooms do
    collection { post :import }
  end
  resources :mentors do
    collection { post :import }
    collection { post :delete_all }
  end
  devise_for :users
  resources :orders do
    collection { get :scan }
    collection { post :scan_student }
  end
  resources :students do
    collection { post :import }
    collection { post :delete_all }
  end
  resources :users
  resources :items do
    collection { post :import }
    member { get :confirm }
  end

  root 'students#home'
  get 'renew/:id' => 'orders#renew'
  get 'return/:id' => 'orders#disable'
  get 'past_orders' => 'orders#old'

  post 'barcode_order' => 'orders#create_barcode_order'
  post 'barcode_checkin' => 'checkins#create_barcode_checkin'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :orders
  has_many :students, through: :orders

  validates :name, presence: true
  validates :category, presence: true
  validates :upc, presence: true
  # if importing a csv, also include quantity

  require 'csv'

  def self.import(file)
  	CSV.foreach(file.path, headers:true) do |row|
  		Item.create! row.to_hash
  	end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy, :confirm]

  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def show
  end

  def edit
  end

  def create
    params[:item][:remaining_quantity] = params[:item][:quantity]
    @item = Item.new(item_params)
    if @item.save
      redirect_to :root, notice: 'Item was successfully created.'
    else
      render :new
    end
  end

  def confirm
  end

  def import
    begin
      Item.import(params[:file])
      redirect_to :root, notice: 'Items successfully created from CSV.'
    rescue
      redirect_to :root, alert: 'Invalid CSV format.'
    end
  end

  def update
    if @item.update(item_params)
      redirect_to items_url, notice: 'Item was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @item.destroy
    redirect_to items_url, notice: 'Item was successfully destroyed.'
  end

  private
  def set_item
    @item = Item.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:name, :category, :quantity, :description, :remaining_quantity, :upc)
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/confirm.html.erb
<body class="hold-transition skin-blue sidebar-mini">
  <div class="wrapper">
    <%= render 'layouts/header' %>
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
      <!-- Content Header (Page header) -->
      <section class="content-header">
        <h1>Successfully Scanned <%= @item.name %></h1>
        <ol class="breadcrumb">
          <li><a href="#"><i class="fa fa-home"></i>Home Page</a></li>
          <li class="active">Add order</li>
        </ol>
      </section>

      <!-- Main content -->
      <section class="content">
        <div class="row">
          <!-- left column -->
          <div class="col-md-6">
           <div class="box box-header">
              
              <div class="box-body">
                <a href="<%= scan_orders_path %>", style='margin-right:20px;'><div class='btn btn-primary'>Back</div></a>
                <a href="<%= item_path(:id => @item.id) %>"><div class='btn btn-success'>Scan Student</div></a>
              </div>
              <!-- /.box-body -->
              
            </div>
            <!-- /.box -->
          </div>
          <!--/.col (right) -->
        </div>
        <!-- /.row -->
      </section>
      <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
    <%= render 'layouts/footer' %>
    <!-- ./wrapper -->
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>
      $(document).ready(function () {
        $.widget.bridge('uibutton', $.ui.button);
        $('.datepicker').datepicker({format: 'yyyy/mm/dd'});
      });
    </script>
  </div>
</body>

app/views/items/edit.html.erb
<body class="hold-transition skin-blue sidebar-mini">
  <div class="wrapper">
    <%= render 'layouts/header' %>
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
      <!-- Content Header (Page header) -->
      <section class="content-header">
        <h1>
          Edit Item
        </h1>
        <ol class="breadcrumb">
          <li>
            <a href="#">
              <i class="fa fa-home"></i>
              Home Page</a>
          </li>
          <li class="active">Edit Item</li>
        </ol>
      </section>

      <!-- Main content -->
      <section class="content">
        <div class="row">
          <!-- left column -->
          <div class="col-md-6">
            <!-- general form elements -->
            <div class="box box-header">
              <div class="box-header with-border">
                <h3 class="box-title">Basic Information</h3>
              </div>
              <!-- /.box-header -->
              <!-- form start -->
              <%= form_for @item do |f| %>
              <% if @item.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(@item.errors.count, "error") %>
                  prohibited this item from being saved:</h2>
                <ul>
                  <% @item.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                  <% end %>
                </ul>
              </div>
              <% end %>
              <div class="box-body">
                <div class="form-group">
                  <label>Name</label>
                  <%= f.text_field :name, class: "form-control", placeholder: "Enter Full Name", required: true %>
                </div>
                <div class="form-group">
                  <label>Description</label>
                  <%= f.text_area :description, class: "form-control", rows: "3", laceholder: "Enter Description"%>
                </div>
                <div class="form-group">
                  <label>Quantity</label>
                  <%= f.number_field :quantity, class: "form-control", placeholder: "Enter Quantity", required: true  %>
                </div>
                <div class="form-group">
                  <label>Remaining Quantity</label>
                  <%= f.number_field :remaining_quantity, class: "form-control", placeholder: "Enter Quantity", required: true  %>
                </div>
                <div class="form-group">
                  <label>Category</label>
                  <%= f.select(:category, [["Laptop", "Laptop"], ["Other", "Other"]], {}, { :class => 'form-control' })%>
                </div>
                <div class="form-group">
                  <label>Barcode UPC</label>
                  <%= f.text_field :upc, class: "form-control", placeholder: "Enter Barcode", required: true %>
                </div>
              </div>
              <!-- /.box-body -->
              <div class="box-footer">
                <%= f.submit "Submit", class: "btn btn-primary"%>
              </div>
              <% end %>

            </div>
            <!-- /.box -->
          </div>
          <!--/.col (right) -->
        </div>
        <!-- /.row -->
      </section>
      <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
    <footer class="main-footer">
      <div class="pull-right hidden-xs">
        <b>Version</b>
        0.1
      </div>
      Content available under
      <a href="http://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Attribution-ShareAlike 4.0</a>.
    </footer>
    <!-- ./wrapper -->
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>
      $.widget.bridge('uibutton', $.ui.button);
    </script>
  </body>

app/views/items/index.html.erb
<body class="hold-transition skin-blue sidebar-mini">
  <div class="wrapper">
    <%= render 'layouts/header' %>
    <div class="content-wrapper">

      <!-- Content Header (Page header) -->
      <section class="content-header">
        <h1>
          Inventory
          <small>Items</small>
        </h1>
        <ol class="breadcrumb">
          <li>
            <a href="#">
              <i class="fa fa-home"></i>
              Home Page</a>
          </li>
          <li class="active">Check Inventory</li>
        </ol>
      </section>

      <section class="content">
        <div class="row">
          <div class="col-xs-12">
            <!-- Main data table -->
            <div class="box">

              <!-- /.box-header -->
              <div class="box-body">
                <table id="example1" class="table table-bordered table-striped">
                  <thead>
                    <tr>
                      <th>ID</th>
                      <th>Category</th>
                      <th>Name</th>
                      <th>Description</th>
                      <th>Quantity</th>
                      <th>Available Qty</th>
                      <th>Edit</th>
                      <th>Delete</th>
                      <th>Borrow</th>
                    </tr>
                  </thead>
                  <tbody>
                    <% @items.each do |item| %>
                    <tr>
                      <td><%= item.id %></td>
                      <td><%= item.category %></td>
                      <td><%= item.name %></td>
                      <td><%= item.description %></td>
                      <td><%= item.quantity %></td>
                      <td><%= item.remaining_quantity %></td>
                      <td><%= link_to 'Edit', edit_item_path(item) %></td>
                      <td><%= link_to 'Delete', item, method: :delete, data: { confirm: 'Are you sure you want to delete this item?' } %></td>
                      <td><%= link_to 'Borrow', new_order_path(item: item.id) %></td>
                    </tr>
                    <% end %>
                  </tbody>
                </table>
              </div>
              <!-- /.box-body -->
            </div>
          </div>
        </div>
      </section>
    </div>
    <%= render 'layouts/footer' %>
  </div>
  <script>
    $(function () {
      $("#example1").DataTable();
      $('#example2').DataTable({
        "paging": true,
        "lengthChange": false,
        "searching": false,
        "ordering": true,
        "info": true,
        "autoWidth": false
      });
    });
  </script>
</body>

app/views/items/new.html.erb
<body class="hold-transition skin-blue sidebar-mini">
  <div class="wrapper">
    <%= render 'layouts/header' %>
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
      <!-- Content Header (Page header) -->
      <section class="content-header">
        <h1>
          Add Item
        </h1>
        <ol class="breadcrumb">
          <li>
            <a href="#">
              <i class="fa fa-home"></i>
              Home Page</a>
          </li>
          <li class="active">Add Item</li>
        </ol>
      </section>

      <!-- Main content -->
      <section class="content">
        <div class="row">
          <!-- left column -->
          <div class="col-md-6">
            <!-- general form elements -->
            <div class="box box-header">
              <div class="box-header with-border">
                <h3 class="box-title">Basic Information</h3>
              </div>
              <!-- /.box-header -->
              <!-- form start -->
              <%= form_for @item do |f| %>
              <% if @item.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(@item.errors.count, "error") %>
                  prohibited this item from being saved:</h2>
                <ul>
                  <% @item.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                  <% end %>
                </ul>
              </div>
              <% end %>
              <div class="box-body">
                <div class="form-group">
                  <label>Name</label>
                  <%= f.text_field :name, class: "form-control", placeholder: "Enter Name", required: true  %>
                </div>
                <div class="form-group">
                  <label>Description</label>
                  <%= f.text_area :description, class: "form-control", rows: "3", laceholder: "Enter Description"%>
                </div>
                <div class="form-group">
                  <label>Quantity</label>
                  <%= f.number_field :quantity, class: "form-control", placeholder: "Enter Quantity", required: true  %>
                </div>
                <div class="form-group">
                  <label>Category</label>
                  <%= f.select(:category, [["Laptop", "Laptop"], ["Other", "Other"]], {}, { :class => 'form-control' })%>
                </div>
                <div class="form-group">
                  <label>Barcode UPC</label>
                  <%= f.text_field :upc, class: "form-control", placeholder: "Enter Barcode", required: true %>
                </div>
              </div>
              <!-- /.box-body -->
              <div class="box-footer">
                <%= f.submit "Submit", class: "btn btn-primary"%>
              </div>
              <% end %>
            </div>
            <!-- /.box -->
          </div>
          <!--/.col (right) -->
        <!-- /.row -->
      <!-- /.content -->

          <!-- right column -->
          <div class="col-md-6">
            <!-- general form elements -->
            <div class="box box-header">
              <div class="box-header with-border">
                <h3 class="box-title">Import CSV</h3>
              </div>
              <!-- /.box-header -->
              <!-- form start -->
                <div class="box-body">
                 <div class="form-group">
                    <label>Select File</label>
                    <%= form_tag(import_items_path, multipart:true) do %>
                      <%= file_field_tag :file, class: "form-control" %>
                      <div class="box-footer">
                        <%= submit_tag "Submit", class: "btn btn-primary" %>
                      </div>
                    <% end %>
                  </div>
                <!-- /.box-body -->
                </div>
            <!-- /.box -->
            </div>
          <!--/.col (right) -->
          </div>
        </div>
        <!-- /.row -->
      </section>
      <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
    <footer class="main-footer">
      <div class="pull-right hidden-xs">
        <b>Version</b>
        0.1
      </div>
      Content available under
      <a href="http://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Attribution-ShareAlike 4.0</a>.
    </footer>
    <!-- ./wrapper -->
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>
      $.widget.bridge('uibutton', $.ui.button);
    </script>
  </body>

app/views/items/show.html.erb
<body class="hold-transition skin-blue sidebar-mini">
  <div class="wrapper">
    <%= render 'layouts/header' %>
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
      <!-- Content Header (Page header) -->
      <section class="content-header">
        <h1>Check out <%= @item.name %></h1>
        <ol class="breadcrumb">
          <li><a href="#"><i class="fa fa-home"></i>Home Page</a></li>
          <li class="active">Add order</li>
        </ol>
      </section>

      <!-- Main content -->
      <section class="content">
        <div class="row">
          <!-- left column -->
          <div class="col-md-6">
           <div class="box box-header">
              <div class="box-header with-border">
                <h3 class="box-title">Scan Student</h3>
              </div>
              
              <div class="box-body">
                <div id='barcode-scanner'></div>
                  <div id='is_room' style="display: none;">
                    <%= -1 %>
                  </div>
                  <div id='item_or_room_id' style="display: none;">
                    <%= @item.id %>
                  </div>
              </div>
              <!-- /.box-body -->
              
            </div>
            <!-- /.box -->
          </div>
          <!--/.col (right) -->
        </div>
        <!-- /.row -->
      </section>
      <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
    <%= render 'layouts/footer' %>
    <!-- ./wrapper -->
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>
      $(document).ready(function () {
        $.widget.bridge('uibutton', $.ui.button);
        $('.datepicker').datepicker({format: 'yyyy/mm/dd'});
      });
    </script>
  </div>
</body>