config/routes.rb
Rails.application.routes.draw do
  resources :checkins
  resources :rooms do
    collection { post :import }
  end
  resources :mentors do
    collection { post :import }
    collection { post :delete_all }
  end
  devise_for :users
  resources :orders do
    collection { get :scan }
    collection { post :scan_student }
  end
  resources :students do
    collection { post :import }
    collection { post :delete_all }
  end
  resources :users
  resources :items do
    collection { post :import }
    member { get :confirm }
  end

  root 'students#home'
  get 'renew/:id' => 'orders#renew'
  get 'return/:id' => 'orders#disable'
  get 'past_orders' => 'orders#old'

  post 'barcode_order' => 'orders#create_barcode_order'
  post 'barcode_checkin' => 'checkins#create_barcode_checkin'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="main-footer">
  <div class="pull-right hidden-xs">
    <b>Version</b>
    0.1
  </div>
  Content available under
  <a href="http://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Attribution-ShareAlike 4.0</a>.
</footer>

app/views/layouts/_header.html.erb
<header class="main-header">
  <!-- Logo -->
  <a href="<%= root_url %>" class="logo">
    <!-- mini logo for sidebar mini 50x50 pixels -->
    <span class="logo-mini">
      <b>A</b>H</span>
    <!-- logo for regular state and mobile devices -->
    <span class="logo-lg">
      <b>ANova Hacks</b>
    </span>
  </a>
  <!-- Header Navbar: style can be found in header.less -->
  <nav class="navbar navbar-static-top">
    <!-- Sidebar toggle button-->
    <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
      <span class="sr-only">Toggle navigation</span>
    </a>
  </nav>
</header>
<!-- Left side column. contains the logo and sidebar -->
<aside class="main-sidebar">
  <!-- sidebar: style can be found in sidebar.less -->
  <section class="sidebar">
    <!-- Sidebar user panel -->
    <div class="user-panel">
      <div class="pull-left image">
        <%= image_tag("anova.png", class: "img-circle") %>
      </div>
      <div class="pull-left info">
        <p><%= current_user.name %></p>
        <a href="<%= edit_user_path(current_user.id) %>">
          <i class="fa fa-edit"></i>
          Edit Profile</a>
        <a href="">
          <%= link_to destroy_user_session_path, method: :delete  do %>
          <i class="fa fa-sign-out"></i>Log Out
        <% end %>
        </a>
      </div>
    </div>
    <!-- sidebar menu: : style can be found in sidebar.less -->
    <ul class="sidebar-menu" data-widget="tree">
      <li class="header">MAIN NAVIGATION</li>
      <li>
        <a href="<%= root_url %>">
          <i class="fa fa-home"></i>
          <span>Home Page</span>
        </a>
      </li>
      <li>
        <a href="<%= items_path %>">
          <i class="fa fa-search"></i>
          <span>Check Inventory</span>
        </a>
      </li>
      <li>
        <a href="<%= orders_path %>">
          <i class="fa fa-history"></i>
          <span>Orders</span>
        </a>
      </li>
      
      <li>
        <a href="<%= scan_orders_path %>">
          <i class="fa fa-laptop"></i>
          <span>Checkout Items</span>
        </a>
      </li>
      <li>
        <a href="<%= rooms_path %>">
          <i class="fa fa-map-marker "></i>
          <span>Check In</span>
        </a>
      </li>
      <li class="treeview">
        <a href="#"><i class="fa fa-plus"></i> <span>Add</span>
              <span class="pull-right-container">
                <i class="fa fa-angle-left pull-right"></i>
              </span>
            </a>
        <ul class="treeview-menu">
          <li>
            <a href=" <%= new_item_path %>">
              <i class="fa fa-search-plus"></i>
              <span>Add Item</span>
            </a>
          </li>
          <li>
            <a href="<%= new_student_path %>">
              <i class="fa fa-user-plus"></i>
              <span>Add Student</span>
            </a>
          </li>
          <li>
            <a href="<%= new_mentor_path %>">
              <i class="fa fa-user-plus"></i>
              <span>Add Mentor</span>
            </a>
          </li>
          <li>
            <a href="<%= new_room_path %>">
              <i class="fa fa-calendar-plus-o"></i>
              <span>Add Room</span>
            </a>
          </li>
        </ul>
      </li>
      <li>
        <a href="/checkins">
          <i class="fa fa-ticket"></i>
          <span>Raffle / Checkins</span>
        </a>
      </li>
    </ul>
  </section>
  <!-- /.sidebar -->
</aside>

app/views/layouts/_notifications.html.erb
<% if flash.present? %>
  <div id="flash">
    <script type="text/javascript">
      toastr.options = {
        "closeButton": false,
        "debug": true,
        "newestOnTop": false,
        "progressBar": false,
        "positionClass": "toast-top-right",
        "preventDuplicates": false,
        "onclick": null,
        "showDuration": "300",
        "hideDuration": "500",
        "timeOut": "1500",
        "extendedTimeOut": "500",
        "showEasing": "swing",
        "hideEasing": "linear",
        "showMethod": "fadeIn",
        "hideMethod": "fadeOut"
      }
      <% flash.each do |f| %>
      <% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'success') %>
      toastr['<%= type %>']('<%= f[1] %>');
      <% end %>
    </script>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ANova Hacks</title>
    <%= csrf_meta_tags %>
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application'%>
    <%= stylesheet_link_tag "AdminLTE.min.css" %>
    <%= stylesheet_link_tag "admin-lte-all-skins.min.css" %>
    <%= stylesheet_link_tag "blue.css" %>
    <%= stylesheet_link_tag "dataTables.bootstrap.css" %>
    <%= stylesheet_link_tag "datepicker3.css" %>

    <%= stylesheet_link_tag "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css" %>
    <%= stylesheet_link_tag "https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css" %>
    <%= javascript_include_tag "https://code.jquery.com/ui/1.11.4/jquery-ui.min.js"%>
    <%= javascript_include_tag "bootstrap3-wysihtml5.all.min.js"%>
    <%= javascript_include_tag "jquery.dataTables.min.js"%>
    <%= javascript_include_tag "dataTables.bootstrap.min.js"%>
    <%= javascript_include_tag "jquery.slimscroll.min.js"%>
    <%= javascript_include_tag "fastclick.js"%>
    <%= javascript_include_tag "admin-lte-app.min.js"%>
    <%= javascript_include_tag "icheck.min.js"%>
    <%= javascript_include_tag "bootstrap-datepicker.js"%>

  </head>
    <%= render 'layouts/notifications' %>
    <%= yield %>
</html>